language: node_js
node_js:
- '4.0'
- '7.0'
after_script: bash <(curl -s https://codecov.io/bash)
sudo: false
deploy:
  - provider: releases
    api_key:
      secure: A8NpISg//NNDq9kOclBemt5KD1SKPpYm/dZzGx2+smOST1EAgriG7oPDO+mE4Umb6omuoajBJxmSIYir3tzKC/GsTQFZaulBtJl5IMUJJigKHosDm5AT7OvriuTtozpJ4J5FrUbUxp6UJzrNPtm7hmPn5Ln/2rMbjiTpUvPmOZk=
    file:
      - "franc.js"
      - "franc-min.js"
      - "franc-all.js"
    on:
      tags: true
      node: '7.0'
